### PR TITLE
Fix index usage in ShapeDeserializer

### PR DESCRIPTION
**Pull request by hauke96**
This fixes issue #223 .

### CODE REVIEW

**Comment by dsmiley** [comment]
ooh yeah, the [iCLA](https://github.com/locationtech/spatial4j/blob/master/CONTRIBUTING.md#filing-an-eca).  It's quick & easy.  Yeah I know -- for 2 lines of code!  Ugh; bureaucracy!

**Comment by hauke96** [comment]
> ooh yeah, the [iCLA](https://github.com/locationtech/spatial4j/blob/master/CONTRIBUTING.md#filing-an-eca). It's quick & easy. Yeah I know -- for 2 lines of code! Ugh; bureaucracy!

I already signed it but there are mismatches with the email addresses. Even after changing my mail address in the eclipse profile the tool wasn't able to match this PR with the account where I signed ECA. I already invested half an hour to find a fix but haven't found anything. Sorry but I'm not willing to invest more time into that.

**Comment by hauke96** [comment]
I just created a new eclipse account with the same username and mail address as here on github. However this PR is still connected to the old account. Can you @dsmiley  change that and re-run the ECA check? Or do I have to close this PR and create a new one?

**Comment by hauke96** [comment]
Just re-committed the change, not everything should be fine. Quick & easy.

**Comment by dsmiley** [comment]
Thank you for perservering!

**Pull request merged**
