### PR TITLE
Using JtsSpatialContextFactory.useJtsMulti to control narrowing of collections.

### PR DESCRIPTION
**Pull request by jdeolive**
This removes the need for custom JtsPolyshapeReader.

### CODE REVIEW

**Comment by jdeolive** [comment]
A couple of additional comments.

- Had to increase the visibility of ShapeFactoryImpl.GeneralShapeMultiShapeBuilder to protected in order to subclass it in JtsShapeFactory
- Had to update WktShapeParserTest to set useJtsMulti to pass in order to the test case to pass as is

**Comment by dsmiley** [comment]
I added a few comments.  Nice work overall (esp. nice to see the test); I'm looking forward to merging it.

**Comment by jdeolive** [comment]
Thanks David. Updated the pull request based on your feedback. Let me know if you want me to squash the commits or if there is anything else that looks off.

**Comment by dsmiley** [comment]
Awesome.  Squash & merge!

(I am personally not too familiar with the squashing of feature branches but it's all your changes (thus a squash wouldn't conceal other's work) and it could very well be one commit so might as well have it be.)

**Comment by jdeolive** [comment]
Cool. Yeah I tend to prefer squashing feature branches into a single commit as long as (a) a single commit makes sense and (b) it doesn't "hide" any other authors work.

**Pull request merged**
