### PR TITLE
add support for jackson serialization

### PR DESCRIPTION
**Pull request by ryantxu**
Here is a quick sketch for how to do that.  This requires changing the project structure so that we can have multiple .jar files

NOTE:  this is not ready to commit -- but want early feedback to see if the direction is OK

### CODE REVIEW

**Comment by dsmiley** [comment]
So is this basically another GeoJSON reader/writer but one using Jackson instead of "Noggit"?  If not please elaborate.  BTW in the future I suggest doing a major refactoring in a commit separate from the commit that does what you want to do.

**Comment by ryantxu** [comment]
> is this basically another GeoJSON reader/writer

no -- it is a serializer/deserializer for Jackson.  Jackson is a system that lets you take any java object and write/read it from some format; json and xml are the most popular.

This module makes it so that if you puy Geometry or Shape in the POJO tree, jackson will write it as WKT  (i'll add some more configs to support the other formats too)

**Comment by dsmiley** [comment]
Oh okay.  I've forgotten; it's been too long since I've used Jackson.  Any way, I'm thinking maybe this could be incorporated into the same spatial4j jar like the other two features that have dependencies?  It's not critical.  If anything deserves it's own jar, it would be a hypothetical spatial4j-jts.  But I rather like the one-jar with optional dependencies strategy we've been going with.

**Comment by panchenko** [comment]
I would suggest
* removing `Spatial4jMapper` (users could use multiple modules)
* renaming `Spatial4jModule` to have `WKT` in class name

**Comment by dsmiley** [comment]
Lost interest Ryan?  The feature looks nice but I'd just prefer a single-jar/module.

**Comment by jdeolive** [comment]
If I can pose another alternative, it would be a separate repo for the jackson stuff. It would keep the main spatial4j build to a single jar file. Users consuming the artifacts via maven would see no difference. I've seen this approach used for other projects to provide jackson bindings. Just a thought.

**Comment by ryantxu** [comment]
The suggestions here have been incorporated into #138

**Pull request closed without merging**
