### PR TITLE
[CORE] Add normalizePoint convenience method

### PR DESCRIPTION
**Pull request by nknize**
Instead of relying on two separate axis normalization methods, this single convenience method normalizes a Point to fall within world bounds, correctly handling antipodal longitudes when latitude values wrap the poles.  Note: randomized testing included

### CODE REVIEW

**Comment by nknize** [comment]
Having normalization logic in the DistanceUtils class is odd to me since its fundamentally associated with the geometry and not exclusive to distance calculations (which is why SpatialContext.norm* totally makes sense).  That was the main reason for placing the test in JtsGeometryTest.  Is there an opposition to decoupling much of those convenience methods from DistanceUtils (say into something a little more logical like a .core.math package)?

**Comment by dsmiley** [comment]
That's a good point -- this doesn't belong in DistanceUtils.  I think a simple SpatialUtils could be fine?  I wince at the suggestion of core.math... lots of Spatial4j is math related :-)

p.s. you may find the Issue list on GitHub interesting to see various discussions of code organization reminiscent of this

**Comment by nknize** [comment]
That sounds good. I also agree on not introducing an overly general .math package. I'll refactor to SpatialUtils and push later tonight or in the morning.

**Comment by nknize** [comment]
Since coordinate normalization is a fundamental dependent on the defined Coordinate Reference System, I went ahead and started laying the foundation for Proj4J integration by way of a new core.crs package.  In staying true to the ContextFactory design, the CRSDelegate will be instantiated by the Context definition and serves as the primary integration point for Proj4J support.

**Comment by ryantxu** [comment]
+1 for this change

Is it still alive?

**Comment by ryantxu** [comment]
hymmm -- I did not try to close this.  I wonder if this is an artifact of making a commit on it.  The button to 'reopen' says:

```
The nknize:enhancement/normPoint branch has no history in common with locationtech:master
```

I bet making the first commit after import to locationtech closed a bunch of pending issues and pull requests!

**Comment by ryantxu** [comment]
hymm -- when i try to see if we can do this manually from:
https://github.com/locationtech/spatial4j/compare/master...nknize:enhancement/normPoint?expand=1

It says:
```
locationtech:master and nknize:enhancement/normPoint are entirely different commit histories.
```

**Pull request closed without merging**
