### PR TITLE
GH-162 handle empty point / shape collection in toString

### PR DESCRIPTION
**Pull request by jeenbroekstra**
Added corner case handling for serializing points and shape collections to string. 

Fixes issue GH-162

### CODE REVIEW

**Comment by dsmiley** [comment]
Thanks!  Please add a CHANGES.md entry and then I look forward to squash-merging this!

**Comment by dsmiley** [comment]
Maybe `GeneralWktTest.java` would be a better existing place to put this assuming we round-trip and also that this is specific to WKT at this time (GeoJSON empty not yet supported -- I don't know for sure)

**Comment by jeenbroekstra** [comment]
I've added a changelog entry - had to force-push as I forgot to sign off at first. Not sure where the conflict comes from as I only added the one line, but I'll leave that in your capable hands :)

**Comment by dsmiley** [comment]
I have some changes that more extensively work across GeoJson as well and testing.  I tried to push to your PR but it was rejected.  Have you seen this?: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork   
If I can't push to your PR than how about I create a new PR with your change and mine on top?   Or I do a PR to _your_ feature branch on your fork?

**Comment by jeenbroekstra** [comment]
Peculiar - the "allow edits from maintainers" option was already enabled, so you should have been able to push to my branch. 

One way to solve this if you create a new feature branch for this change in the main repo, then re-target this PR to that feature branch, merge it, and then do your own additional changes on top. But if you prefer doing a PR on my fork instead that's fine too - whatever works for you :)

**Comment by dsmiley** [comment]
I was mistaken; my initial attempts to push to your branch were actually to a new branch and not to your existing.  I corrected that and as you can see they are here now.

**Pull request merged**
