### PR TITLE
support polyshape encoding

### PR DESCRIPTION
**Pull request by ryantxu**
(this is not ready yet...) I am trying to restore the branch from pre-eclipse.... and having trouble :(

### CODE REVIEW

**Comment by dsmiley** [comment]
Let me know when you'd like me to give this a review. Are you trying to get this into 5.0?

**Comment by ryantxu** [comment]
@dsmiley can you take a look?

**Comment by ryantxu** [comment]
@dsmiley, thanks for taking a look!  I think i have addressed your questions here.  

I am interested to see how this is if we use it rather than BinaryCodec to encode shapes in lucene.  My initial tests show ~1/2 the size  (obviously this only works isGeo=true -- and has some rounding errors)

**Comment by dsmiley** [comment]
I think it's basically ready to be merged.  More docs/info about the Polyshape format would be nice but that's not a hold-up now.

**Comment by ryantxu** [comment]
thanks for looking -- i'll merge and we can improve javadoc/tests/FORMATS.md as we test more.  In particular, i want a javascript example showing the output on a map

**Pull request merged**
