### PR TITLE
Fix MultiPoint serialize not calling writeEndObject

### LINKED ISSUE #210: Serializing a list of MultiPoint geometry with jackson throws a JsonGenerationException
Hi,

I went into an error when serializing a list of MultiPoint geometry with jackson.
It seems like the jackson generator context has been changed by the `GeometryAsGeoJSONSerializer` and not set back.

You can reproduce by running the following:

```java
import java.util.List;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.MultiPoint;
import org.locationtech.jts.geom.Point;
import org.locationtech.spatial4j.io.jackson.ShapesAsGeoJSONModule;

import com.fasterxml.jackson.databind.ObjectMapper;

public class Main {

    public static void main(String[] args) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new ShapesAsGeoJSONModule());

        GeometryFactory geometryFactory = new GeometryFactory();

        Point point = geometryFactory.createPoint(new Coordinate(100, 100));
        MultiPoint multiPoint = geometryFactory.createMultiPoint(new Point[] { point });
        System.out.println(objectMapper.writeValueAsString(List.of(point)));
        System.out.println(objectMapper.writeValueAsString(List.of(multiPoint)));
    }

}
```

It leads to the following output:
```
[{"type":"Point","coordinates":[100.0,100.0]}]
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Current context not Array but Object
        at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2657)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeEndArray(WriterBasedJsonGenerator.java:295)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:80)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
        at Main.main(Main.java:22)
```

The fix seems quite simple: https://github.com/PapaStan/spatial4j/commit/142d3f88ad05a79319ebda8385a00920ffbd9582

### PR DESCRIPTION
**Pull request by PapaStan**
Fixes #210

### CODE REVIEW

**Comment by dsmiley** [comment]
Thanks!
Can you please sign the ECA as mentioned here: https://github.com/locationtech/spatial4j/blob/master/CONTRIBUTING.md#filing-an-eca 
It's quick and easy.  
All for a one-liner, I know you're thinking ;-)

**Comment by PapaStan** [comment]
Yes, I have to wait for my employer to agree with me signing the ECA as I ran into this in my working time.

Sorry for the wait

**Comment by dsmiley** [comment]
Oh, and you can also give yourself credit in CHANGES.md

**Comment by PapaStan** [comment]
Done

**Comment by PhilippauxAdrien** [comment]
Thank you for this PR

**Pull request merged**
