### PR TITLE
Some code smell reduction

### PR DESCRIPTION
**Pull request by matteobaccan**
Hi

I have analyzed the source code with a static analyzer and I have removed some code smell

- Missing override
- Removed unused parameters
- Unused assignment
- Boolean literals redundant
- Unused import
- Catches combined
- Return redundant 

All the best
matteo baccan

### CODE REVIEW

**Comment by matteobaccan** [comment]
Sorry for the wrong commit. I have signed the commit after the first pull request

**Comment by dsmiley** [comment]
Thanks!
You just need to digitally sign the [Eclipse Contributor Agreement](http://www.eclipse.org/legal/ECA.php), which is a one-time thing for all of Eclipse.
I recently heard git "-S" is no longer a requirement at ECA.  I will remove that step from CONTRIBUTING.md

**Comment by matteobaccan** [comment]
Hi

I have digitally signed the ECA

Tell me if it's OK

al the best
matteo baccan

**Comment by dsmiley** [comment]
Not yet anyway... click "Details" link on the PR checks for eclipsefdn/eca.

**Comment by matteobaccan** [comment]
I have clicked, now it's ok  :)
Thank you for the support

**Pull request merged**
