### PR TITLE
Add JtsSpatialContext.makeShapeFromGeometry(geom) …

### PR DESCRIPTION
**Pull request by dsmiley**
…to be used instead of makeShape(geom) usually.

* makeShapeFromGeometry uses the "dateline rule", "validation rule" and "auto index" settings. As such, all 3 IO formats now use it.
* makeShapeFromGeometry converts GeometryCollection into ShapeCollection, recursively.
* makeShapeFromGeometry detects JTS Point & LineString and calls corresponding factory methods on JtsSpatialContext.

At a future point in time I think we should refactor the placement of the "dateline rule", "validation rule" and "auto index" state so that any format can use it.  It would be an API break right now though.

### CODE REVIEW

**Comment by dsmiley** [comment]
Any thoughts on this one @ryantxu (or anyone)?  If not I'll merge this weekend.

**Comment by dsmiley** [comment]
Correction: this patch PR does not incorporate use of the dateline rule, which is in turn only used by Polygon -> Rectangle conversion, and that only happens in JtsWKTReader.  The "ENVELOPE" syntax isn't broadly used and so many apps use a standard polygon representation.  Our "Polyshape" format has a native rect type so no need to do conversion there.  GeoJSON has no native rect.  I think GeoJSON should behave similarly and do the conversion.  @jdeolive  what do you think?

**Comment by jdeolive** [comment]
+1 on making GeoJSON do the conversion. I think having all the formats apply the same rules makes most sense.

**Comment by ryantxu** [comment]
looks good

**Pull request merged**
